### ISSUE TITLE
Balsamic wireframes

### ISSUE THREAD

**Issue by bitmole** [idealoop/virtualbar#1]
Please create wireframes, and put them into a doc directory.

**Comment by matejtaborsky** [comment]
please provide me with more info, what kind of wireframes?

**Comment by bitmole** [comment]
Balsamiq wireframes outlining the functionality of each screen. Please collaborate with Miso on details. We're mirroring the functionality of http://virtualbar.responsibility.org with improvements. Miso has details in an earlier email.

**Comment by matejtaborsky** [comment]
I have discussed it with Miso today morning. After I finish tostitos, I will prepare wireframes. Is there deadline?

**Comment by michaelniepel** [comment]
Mato, just create something as soon as possible so we can start showing the client some work and kickstart the project.  Copy this screen http://virtualbar.responsibility.org/ and create another one for setting "users dimensions"

**Comment by bitmole** [comment]
Guys, we just need balsamiq wireframes at this point to get client's approval on functionality and UX. I'll get started on them today if you don't have time. Let me know. I'd like to deliver first revision of wireframes by Monday.

**Comment by michaelniepel** [comment]
bump, Mato we start today with framing.

**Comment by michaelniepel** [comment]
![main](https://cloud.githubusercontent.com/assets/719261/10129439/2c69a06e-65be-11e5-9cfb-ecd46efd7932.png)
![presentation](https://cloud.githubusercontent.com/assets/719261/10129440/2c6e3e8a-65be-11e5-84d8-caf403e94c6f.png)
![setting_age](https://cloud.githubusercontent.com/assets/719261/10129441/2c72ef20-65be-11e5-9f3c-497f8ea4b403.png)
![side-navigation](https://cloud.githubusercontent.com/assets/719261/10129442/2c791eae-65be-11e5-8d5f-976d4ec6f6fb.png)

**Comment by michaelniepel** [comment]
attached lead design from Stano

**Comment by matejtaborsky** [comment]
please review first version of wireframes: https://www.dropbox.com/sh/5fkd6l2rr47nu9a/AADdzXYEZwJ-rlmq3KJuH2jfa?dl=0

**Comment by michaelniepel** [comment]
For the + plus button to add drink/friend/food, one solution could be:
TAP - add a drink
LONG TAP (HOLD) - display a menu (right click on computers) http://nobitagit.github.io/ng-material-floating-button/angular-material.html http://ionicframework.com/docs/api/directive/onHold/

**Comment by michaelniepel** [comment]
http://heelhook.github.io/chardin.js/ this might be useful

**Comment by bitmole** [comment]
That's not obvious enough. How is the user going to know that a long tap functions differently from a normal one? 
What about this: User taps on the plus button, and gets a prompt to select "Drink" or "Eat". I'd also include "Drink", "Eat" to the navigation slideout. I'd make adding a friend contextually obvious by the plus sigh with person when the friends list screen is displayed.

**Comment by michaelniepel** [comment]
[Uploading virtualbar-wireframes.pdf…]()

**Comment by matejtaborsky** [comment]
Updated wireframes:
[virtualbar-wireframes-v2.pdf](https://github.com/idealoop/virtualbar/files/7903/virtualbar-wireframes-v2.pdf)
