### ISSUE TITLE
Status bar overlaps webview

### ISSUE THREAD

**Issue by michaelniepel** [idealoop/virtualbar#28]
Enlarge the md-toolbar

**Comment by michaelniepel** [comment]
todo: check how this works on android

**Comment by michaelniepel** [comment]
Brano, please check on android, if the nav bar is too big, we should use classes for ios only (ionic provided).

**Comment by publix** [comment]
On android toolbar is as high as on web, it means it is too big. It's not just about style. Status bar behaves differently depending on version of iOS. First of all, we need try to figure out, why toolbar overlays status bar on iOS, even if it is explicitly disabled.
