### ISSUE TITLE
black transition between views

### ISSUE THREAD

**Issue by michaelniepel** [idealoop/virtualbar#30]
https://github.com/driftyco/ionic/issues/2969

**Comment by michaelniepel** [comment]
seems abtract states, break transitions

**Comment by publix** [comment]
http://forum.ionicframework.com/t/problem-with-transition-between-abstract-views/14402
Removing abstract:true can fix problem

**Comment by michaelniepel** [comment]
checking it, it breaks the logic for now

**Comment by michaelniepel** [comment]
This works, but please check if we can actually "close" the sub routes, just like we were talking yesterday.

**Comment by michaelniepel** [comment]
states work with latest changes, wont do this right now
