### ISSUE TITLE
Setup Google Play Store

### ISSUE THREAD

**Issue by michaelniepel** [idealoop/virtualbar#34]
For the "localizable information" - we want the name to be Virtual Bar and the URL to be www.responsibility.org 

Google Developer	
centurycouncileducation@gmail.com	
Recovery email is charles.paullin@responsibility.org
centurycouncil2023

**Comment by michaelniepel** [comment]
Brano, if you have some time, please look at this and post all assets we need here

**Comment by publix** [comment]
Minimum required assets:

Google Play:
1. Hi-Res Icon 512x512px, 32bit PNG with alpha channel
2. Main graphics (banner) 1024x500px, JPG or 24bit PNG without alpha channel

Android application:
1. Launcher icon: Hi-Res Icon 512x512px
2. Splash screen: 1200x1200 px minimum

All artwork will be generated with ionic tools, more info at this link:
http://ionicframework.com/docs/cli/icon-splashscreen.html

**Comment by publix** [comment]
Icon and splash screen shows up on android device. For splash screen I suggest to use image with higher density.

**Comment by michaelniepel** [comment]
![featured_1024x500](https://cloud.githubusercontent.com/assets/719261/11059262/f07f2d92-8798-11e5-9cdc-b30f3cf40430.png)
![1024](https://cloud.githubusercontent.com/assets/719261/11059263/f2475456-8798-11e5-87ee-1a10c950054b.png)

**Comment by michaelniepel** [comment]
Brano, attached you have the feature graphics and app icon

**Comment by publix** [comment]
Android application is uploaded to Play Store for alpha testing, currently in status pending publication.
Google Store Listing is set up as well.
