### ISSUE TITLE
Add guys from Responsibility to android beta testing

### ISSUE THREAD

**Issue by michaelniepel** [idealoop/virtualbar#43]
Brano, please add sam.nathews@responsibility.org and leslie.kimball@responsibility.org to beta Android beta testing, how can they download the app?

**Comment by publix** [comment]
Alpha/Beta testing program is open to public users, anyone can join by visiting this url link: https://play.google.com/apps/testing/com.FAAR.VirtualBar

These criteria must be met to download application
Users need a Google Account (@gmail.com) or a Google Apps account to join a test.
Users need to have android 5.1 installed on device
