### ISSUE TITLE
CSS theme

### ISSUE THREAD

**Issue by michaelniepel** [idealoop/virtualbar#6]
Mateeezh, please check this theme if it suites our needs: https://market.ionic.io/themes/ionic-material-design

**Comment by michaelniepel** [comment]
https://github.com/delta98/ionic-material-design-lite

**Comment by michaelniepel** [comment]
preferably create a new branch so we can compare

**Comment by publix** [comment]
branch with new theme was created
https://github.com/idealoop/virtualbar/tree/ionic-material-design-lite

**Comment by michaelniepel** [comment]
ionic-material-design-lite looks better to me

**Comment by michaelniepel** [comment]
@matejtaborsky get familiar with this: https://material.angularjs.org/latest/Theming/01_introduction
