### ISSUE TITLE
Create profile flow

### ISSUE THREAD

**Issue by michaelniepel** [idealoop/virtualbar#8]

**Comment by michaelniepel** [comment]
why did you remove https://github.com/idealoop/virtualbar/blob/master/www/js/app.js#L258 ? app cannot start on device now

**Comment by michaelniepel** [comment]
Default sidemenu template, pure ionic
![screen shot 2015-10-18 at 11 44 28](https://github-cloud.s3.amazonaws.com/assets/719261/10565268/159f85b4-75cd-11e5-8117-b9ef0bfc877f.png)

**Comment by michaelniepel** [comment]
@publix ion-nav-view in default sidemenu ionic template
![screen shot 2015-10-18 at 19 15 52](https://github-cloud.s3.amazonaws.com/assets/719261/10565273/25c7f03e-75cd-11e5-955d-1ca9e07215e9.png)

**Comment by publix** [comment]
@michaelniepel you are right, two components have it's own navigation history stack

**Comment by michaelniepel** [comment]
The flow works as expected
